version: '3.8'

services:

  db:
    platform: linux/x86_64
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: 'always'
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password    
    networks:
      - shared-network

  backend:
    restart: unless-stopped
    # image: online-store-backend
    build: ./backend
    ports:
      - 3001:3001
    networks:
      - shared-network
    depends_on:
      - "db"
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=3308
      - JWT_SECRET=abobrinha

  frontend:
    restart: unless-stopped
    # image: online-strore-frontend
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - shared-network
    depends_on:
      - "backend"
   

networks:
  shared-network:
    driver: 'bridge'
